workflows:
  ios-testflight:
    name: iOS TestFlight Release
    max_build_duration: 120
    environment:
      xcode: 14.1
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          gem install cocoapods
          pod install
    cache:
      paths:
        - ~/.pub-cache
        - ios/Pods
    targets:
      - ios
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      testflight:
        api_key: $TESTFLIGHT_API_KEY  # Codemagic environment variable for TestFlight API key
        api_key_id: $TESTFLIGHT_API_KEY_ID  # Codemagic environment variable for TestFlight API key ID
        api_issuer_id: $TESTFLIGHT_API_ISSUER_ID  # Codemagic environment variable for API issuer ID
        release_notes: |
          "Automatic build and upload to TestFlight"
        notify_testers: true
