workflows:
  ios:
    name: iOS CI/CD Workflow
    max_build_duration: 60 # Set a timeout for your build process (in minutes)
    environment:
      xcode: 14.3 # Specify the version of Xcode you are using
      cocoapods: true # Ensure CocoaPods is available in the environment (if you're using it)

    scripts:
      - name: Install dependencies
        script: |
          # Install CocoaPods dependencies (if needed)
          gem install cocoapods
          pod install --repo-update
          
      - name: Build iOS app
        script: |
          # Clean any previous builds and perform a new build using xcodebuild
          xcodebuild clean -workspace YourWorkspace.xcworkspace -scheme YourScheme -configuration Release -sdk iphoneos
          xcodebuild archive -workspace YourWorkspace.xcworkspace -scheme YourScheme -configuration Release -sdk iphoneos -archivePath $CM_BUILD_DIR/YourApp.xcarchive
          
      - name: Export IPA
        script: |
          # Export the IPA file from the archive
          xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/YourApp.xcarchive -exportOptionsPlist exportOptions.plist -exportPath $CM_BUILD_DIR/YourApp.ipa

    artifacts:
      - $CM_BUILD_DIR/YourApp.ipa # Define the .ipa file as an artifact for download

    publishing:
      testflight:
        api_key: $TESTFLIGHT_API_KEY # Your TestFlight API Key (configured as an environment variable)
        ipa_path: $CM_BUILD_DIR/YourApp.ipa
        app_identifier: "com.yourcompany.yourapp" # Your app's unique identifier
        team_id: $TEAM_ID # Your Apple Developer team ID
        username: $APPLE_DEV_USERNAME # Your Apple Developer account username
        password: $APPLE_DEV_PASSWORD # Your Apple Developer account password (Use app-specific password if available)

    # Optional: Add a post-processing step if needed
    post_process:
      - name: Clean up after build
        script: |
          # Optionally, delete temporary files or caches after the build
          rm -rf $CM_BUILD_DIR/YourApp.xcarchive
