

ios-native:

  environment:

    vars:

      BUNDLE_ID: "com.hamid.arkit.new"

      XCODE_WORKSPACE: "Tracked Images.xcworkspace" # <-- Name of your Xcode workspace

      XCODE_SCHEME: "Tracked Images" # <-- Name of your Xcode scheme

scripts:

  # ...

  - name: Build ipa for distribution

    script: | 

      xcode-project build-ipa \

        --workspace "$CM_BUILD_DIR/$XCODE_WORKSPACE" \

        --scheme "$XCODE_SCHEME"

artifacts:

  - build/ios/ipa/*.ipa

  - /tmp/xcodebuild_logs/*.log

  - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app

  - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
